name: flutter_googlemaps_test
description: Flutter Google Maps test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:

  sdk: ">=2.17.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  geolocator: ^8.2.1
  url_launcher: ^6.1.2
  google_maps_flutter: ^2.1.6

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
